// AUTO-GENERATED - DO NOT EDIT
// Generated by eni

export interface ProductDisplay {
  title: string;
  subtitle?: string;
  price: string;
  period?: string;
  badge: string | null;
  features: string[];
  highlighted: boolean;
  cta: string;
}

export interface GeneratedProduct {
  slug: string;
  productId: string | null;
  name: string;
  type: "subscription" | "one_time" | "free";
  display: ProductDisplay;
}

export const sandboxProducts: GeneratedProduct[] = [
  {
    slug: "pro-monthly",
    productId: "b11de49b-1588-4283-be99-e8369899d7d1",
    name: "Pro Monthly",
    type: "subscription",
    display: {
      title: "Pro",
      subtitle: "Billed monthly",
      price: "$19",
      period: "/month",
      badge: null,
      features: ["Unlimited projects","Priority support","Advanced analytics","API access"],
      highlighted: false,
      cta: "Get Started",
    },
  },
  {
    slug: "pro-yearly",
    productId: "114d3505-22e6-4718-89a2-560bba9b7d40",
    name: "Pro Yearly",
    type: "subscription",
    display: {
      title: "Pro",
      subtitle: "Billed yearly",
      price: "$190",
      period: "/year",
      badge: "2 months free",
      features: ["Unlimited projects","Priority support","Advanced analytics","API access","Early access to new features"],
      highlighted: true,
      cta: "Get Started",
    },
  },
  {
    slug: "lifetime",
    productId: "201a345e-0b86-4602-8583-d87a83a2b18e",
    name: "Lifetime Access",
    type: "one_time",
    display: {
      title: "Lifetime",
      subtitle: "Pay once, own forever",
      price: "$299",
      period: undefined,
      badge: "Best Deal",
      features: ["Everything in Pro","Lifetime updates","Priority support forever","Exclusive founder badge"],
      highlighted: false,
      cta: "Buy Now",
    },
  }
] as const;

export const productionProducts: GeneratedProduct[] = [
  {
    slug: "pro-monthly",
    productId: null,
    name: "Pro Monthly",
    type: "subscription",
    display: {
      title: "Pro",
      subtitle: "Billed monthly",
      price: "$19",
      period: "/month",
      badge: null,
      features: ["Unlimited projects","Priority support","Advanced analytics","API access"],
      highlighted: false,
      cta: "Get Started",
    },
  },
  {
    slug: "pro-yearly",
    productId: null,
    name: "Pro Yearly",
    type: "subscription",
    display: {
      title: "Pro",
      subtitle: "Billed yearly",
      price: "$190",
      period: "/year",
      badge: "2 months free",
      features: ["Unlimited projects","Priority support","Advanced analytics","API access","Early access to new features"],
      highlighted: true,
      cta: "Get Started",
    },
  },
  {
    slug: "lifetime",
    productId: null,
    name: "Lifetime Access",
    type: "one_time",
    display: {
      title: "Lifetime",
      subtitle: "Pay once, own forever",
      price: "$299",
      period: undefined,
      badge: "Best Deal",
      features: ["Everything in Pro","Lifetime updates","Priority support forever","Exclusive founder badge"],
      highlighted: false,
      cta: "Buy Now",
    },
  }
] as const;

export function getProducts(env: "sandbox" | "production"): GeneratedProduct[] {
  return env === "sandbox" ? sandboxProducts : productionProducts;
}

/**
 * BetterAuth checkout products format
 * Only includes products with a valid polarProductId
 */
export function getCheckoutProducts(env: "sandbox" | "production") {
  return getProducts(env)
    .filter((p) => p.productId !== null)
    .map((p) => ({
      productId: p.productId as string,
      slug: p.slug,
    }));
}

/**
 * Get products formatted for pricing page display
 * Only includes products intended for display (with valid features)
 */
export function getDisplayProducts(env: "sandbox" | "production") {
  return getProducts(env).filter((p) => p.display.features.length > 0);
}
