// AUTO-GENERATED - DO NOT EDIT
// Generated by eni

export interface GeneratedMeter {
  slug: string;
  name: string;
  polarMeterId: string | null;
  eventNames: string[];
}

export const sandboxMeters = [
  {
    slug: "llm-tokens",
    name: "LLM Tokens",
    polarMeterId: "d1e2f3a4-5678-9abc-def0-1234567890ab",
    eventNames: ["use-credit"],
  },
] as const satisfies readonly GeneratedMeter[];

export type MeterSlug = (typeof sandboxMeters)[number]["slug"];

export type MeterEventNames<S extends MeterSlug> = Extract<
  (typeof sandboxMeters)[number],
  { slug: S }
>["eventNames"][number];

export const productionMeters = [
  {
    slug: "llm-tokens",
    name: "LLM Tokens",
    polarMeterId: null,
    eventNames: ["use-credit"],
  },
] as const satisfies readonly GeneratedMeter[];

export function getMeters(
  env: "sandbox" | "production"
): readonly GeneratedMeter[] {
  return env === "sandbox" ? sandboxMeters : productionMeters;
}

export function getMeter(
  env: "sandbox" | "production",
  slug: MeterSlug
): GeneratedMeter | undefined {
  return getMeters(env).find((m) => m.slug === slug);
}

/**
 * Resolves an event name to a human-readable meter display name.
 * Falls back to the raw event name if no matching meter is found.
 */
export function resolveEventDisplayName(
  env: "sandbox" | "production",
  eventName: string
): string {
  const meters = getMeters(env);
  const meter = meters.find((m) => m.eventNames.includes(eventName));
  return meter?.name ?? eventName;
}
