// AUTO-GENERATED - DO NOT EDIT
// Generated by eni

export interface ProductDisplay {
  title: string;
  subtitle?: string;
  price: string;
  period?: string;
  badge: string | null;
  features: string[];
  highlighted: boolean;
  cta: string;
}

export interface GeneratedProduct {
  slug: string;
  productId: string | null;
  name: string;
  type: "subscription" | "one_time" | "free";
  display: ProductDisplay;
}

export const sandboxProducts: GeneratedProduct[] = [
  {
    slug: "ai-workflow-config",
    productId: "0e320f8f-5ed2-4cda-8627-a9e953e2b5c2",
    name: "AI workflow config",
    type: "one_time",
    display: {
      title: "AI workflow config",
      subtitle: "One time purchase / Lifetime updates",
      price: "$50",
      period: undefined,
      badge: null,
      features: ["Ralph loop prompts","Claude code commands and skills"],
      highlighted: false,
      cta: "Get access to the repository",
    },
  },
  {
    slug: "ai-workflow-guide",
    productId: "216a19f1-7d22-4a07-9240-224431859239",
    name: "AI Workflow guide",
    type: "one_time",
    display: {
      title: "AI Workflow guide",
      subtitle: "One time purchase",
      price: "$30",
      period: undefined,
      badge: null,
      features: ["Practical guide on how to use ai","Tips on how to guide ai like pro"],
      highlighted: false,
      cta: "Read the guide",
    },
  },
] as const;

export const productionProducts: GeneratedProduct[] = [
] as const;

export function getProducts(env: "sandbox" | "production"): GeneratedProduct[] {
  return env === "sandbox" ? sandboxProducts : productionProducts;
}

/**
 * BetterAuth checkout products format
 * Only includes products with a valid polarProductId
 */
export function getCheckoutProducts(env: "sandbox" | "production") {
  return getProducts(env)
    .filter((p) => p.productId !== null)
    .map((p) => ({
      productId: p.productId as string,
      slug: p.slug,
    }));
}

/**
 * Get products formatted for pricing page display
 * Only includes products intended for display (with valid features)
 */
export function getDisplayProducts(env: "sandbox" | "production") {
  return getProducts(env).filter((p) => p.display.features.length > 0);
}
